// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GenderEnum string

const (
	GenderEnumMale    GenderEnum = "male"
	GenderEnumFemale  GenderEnum = "female"
	GenderEnumOther   GenderEnum = "other"
	GenderEnumUnknown GenderEnum = "unknown"
)

func (e *GenderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderEnum(s)
	case string:
		*e = GenderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderEnum: %T", src)
	}
	return nil
}

type NullGenderEnum struct {
	GenderEnum GenderEnum
	Valid      bool // Valid is true if GenderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GenderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderEnum), nil
}

type CoreCharacter struct {
	ID                uuid.UUID
	Name              string
	Description       pgtype.Text
	RaceID            uuid.UUID
	Gender            GenderEnum
	BirthDate         pgtype.Date
	BirthPlace        pgtype.Text
	HeightCm          pgtype.Int2
	WeightKg          pgtype.Int2
	BodyFatPercentage pgtype.Numeric
	SizeTop           pgtype.Int2
	SizeMiddle        pgtype.Int2
	SizeBottom        pgtype.Int2
	Version           int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type Race struct {
	ID   uuid.UUID
	Name string
}
