// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCharacters = `-- name: CountCharacters :one
SELECT COUNT(*) FROM core_characters
WHERE deleted_at IS NULL
  AND ($1::uuid[] IS NULL OR id = ANY($1::uuid[]))
`

func (q *Queries) CountCharacters(ctx context.Context, ids []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCharacters, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCharacter = `-- name: CreateCharacter :exec

INSERT INTO core_characters (
    id, name, description, race_id, gender, birth_date, birth_place,
    height_cm, weight_kg, body_fat_percentage, size_top, size_middle, size_bottom,
    version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6::date, $7,
    $8::smallint, $9::smallint,
    $10::numeric,
    $11::smallint, $12::smallint, $13::smallint,
    $14, $15, $16
)
`

type CreateCharacterParams struct {
	ID                uuid.UUID
	Name              string
	Description       pgtype.Text
	RaceID            uuid.UUID
	Gender            GenderEnum
	BirthDate         pgtype.Date
	BirthPlace        pgtype.Text
	HeightCm          pgtype.Int2
	WeightKg          pgtype.Int2
	BodyFatPercentage pgtype.Numeric
	SizeTop           pgtype.Int2
	SizeMiddle        pgtype.Int2
	SizeBottom        pgtype.Int2
	Version           int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

// character / race の SQL。書き込みの不変条件（楽観ロック・論理削除）は
// character-db 側の DB 関数 update_character / soft_delete_character に集約済みで、
// ここではそれを呼ぶだけ。読み取りは races を JOIN して race 名を展開する。
func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) error {
	_, err := q.db.Exec(ctx, createCharacter,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RaceID,
		arg.Gender,
		arg.BirthDate,
		arg.BirthPlace,
		arg.HeightCm,
		arg.WeightKg,
		arg.BodyFatPercentage,
		arg.SizeTop,
		arg.SizeMiddle,
		arg.SizeBottom,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRace = `-- name: CreateRace :exec
INSERT INTO races (id, name) VALUES ($1, $2)
`

type CreateRaceParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateRace(ctx context.Context, arg CreateRaceParams) error {
	_, err := q.db.Exec(ctx, createRace, arg.ID, arg.Name)
	return err
}

const deleteRace = `-- name: DeleteRace :execrows
DELETE FROM races WHERE id = $1
`

func (q *Queries) DeleteRace(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCharacter = `-- name: GetCharacter :one
SELECT c.id, c.name, c.description, c.race_id, c.gender, c.birth_date, c.birth_place, c.height_cm, c.weight_kg, c.body_fat_percentage, c.size_top, c.size_middle, c.size_bottom, c.version, c.created_at, c.updated_at, c.deleted_at, r.name AS race_name
FROM core_characters c
LEFT JOIN races r ON r.id = c.race_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCharacterRow struct {
	ID                uuid.UUID
	Name              string
	Description       pgtype.Text
	RaceID            uuid.UUID
	Gender            GenderEnum
	BirthDate         pgtype.Date
	BirthPlace        pgtype.Text
	HeightCm          pgtype.Int2
	WeightKg          pgtype.Int2
	BodyFatPercentage pgtype.Numeric
	SizeTop           pgtype.Int2
	SizeMiddle        pgtype.Int2
	SizeBottom        pgtype.Int2
	Version           int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	RaceName          pgtype.Text
}

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (GetCharacterRow, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i GetCharacterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RaceID,
		&i.Gender,
		&i.BirthDate,
		&i.BirthPlace,
		&i.HeightCm,
		&i.WeightKg,
		&i.BodyFatPercentage,
		&i.SizeTop,
		&i.SizeMiddle,
		&i.SizeBottom,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RaceName,
	)
	return i, err
}

const getRace = `-- name: GetRace :one
SELECT id, name FROM races WHERE id = $1
`

func (q *Queries) GetRace(ctx context.Context, id uuid.UUID) (Race, error) {
	row := q.db.QueryRow(ctx, getRace, id)
	var i Race
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT c.id, c.name, c.description, c.race_id, c.gender, c.birth_date, c.birth_place, c.height_cm, c.weight_kg, c.body_fat_percentage, c.size_top, c.size_middle, c.size_bottom, c.version, c.created_at, c.updated_at, c.deleted_at, r.name AS race_name
FROM core_characters c
LEFT JOIN races r ON r.id = c.race_id
WHERE c.deleted_at IS NULL
  AND ($1::uuid[] IS NULL OR c.id = ANY($1::uuid[]))
ORDER BY c.created_at ASC
LIMIT NULLIF($3::bigint, 0)
OFFSET $2::bigint
`

type ListCharactersParams struct {
	Ids []uuid.UUID
	Off int64
	Lim int64
}

type ListCharactersRow struct {
	ID                uuid.UUID
	Name              string
	Description       pgtype.Text
	RaceID            uuid.UUID
	Gender            GenderEnum
	BirthDate         pgtype.Date
	BirthPlace        pgtype.Text
	HeightCm          pgtype.Int2
	WeightKg          pgtype.Int2
	BodyFatPercentage pgtype.Numeric
	SizeTop           pgtype.Int2
	SizeMiddle        pgtype.Int2
	SizeBottom        pgtype.Int2
	Version           int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	RaceName          pgtype.Text
}

func (q *Queries) ListCharacters(ctx context.Context, arg ListCharactersParams) ([]ListCharactersRow, error) {
	rows, err := q.db.Query(ctx, listCharacters, arg.Ids, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCharactersRow{}
	for rows.Next() {
		var i ListCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RaceID,
			&i.Gender,
			&i.BirthDate,
			&i.BirthPlace,
			&i.HeightCm,
			&i.WeightKg,
			&i.BodyFatPercentage,
			&i.SizeTop,
			&i.SizeMiddle,
			&i.SizeBottom,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaces = `-- name: ListRaces :many
SELECT id, name FROM races ORDER BY name ASC
`

func (q *Queries) ListRaces(ctx context.Context) ([]Race, error) {
	rows, err := q.db.Query(ctx, listRaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Race{}
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCharacter = `-- name: SoftDeleteCharacter :exec
SELECT soft_delete_character($1)
`

// 物理 DELETE せず deleted_at を立てる。不在/削除済みは SQLSTATE 'CH404' を RAISE。
func (q *Queries) SoftDeleteCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCharacter, id)
	return err
}

const updateCharacter = `-- name: UpdateCharacter :exec
SELECT update_character(
    $1,
    $2::bigint,
    $3,
    $4,
    $5,
    $6,
    $7::date,
    $8,
    $9::smallint,
    $10::smallint,
    $11::numeric,
    $12::smallint,
    $13::smallint,
    $14::smallint
)
`

type UpdateCharacterParams struct {
	ID                uuid.UUID
	ExpectedVersion   pgtype.Int8
	Name              string
	Description       string
	RaceID            uuid.UUID
	Gender            GenderEnum
	BirthDate         pgtype.Date
	BirthPlace        string
	HeightCm          pgtype.Int2
	WeightKg          pgtype.Int2
	BodyFatPercentage pgtype.Numeric
	SizeTop           pgtype.Int2
	SizeMiddle        pgtype.Int2
	SizeBottom        pgtype.Int2
}

// 楽観ロック(version 検査+1)と soft-delete フィルタは関数内で行う。
// expected_version が NULL なら version 検査をスキップ（強制更新）。
// 競合時は SQLSTATE 'CH412'、不在/削除済みは 'CH404' を RAISE する。
func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) error {
	_, err := q.db.Exec(ctx, updateCharacter,
		arg.ID,
		arg.ExpectedVersion,
		arg.Name,
		arg.Description,
		arg.RaceID,
		arg.Gender,
		arg.BirthDate,
		arg.BirthPlace,
		arg.HeightCm,
		arg.WeightKg,
		arg.BodyFatPercentage,
		arg.SizeTop,
		arg.SizeMiddle,
		arg.SizeBottom,
	)
	return err
}

const updateRace = `-- name: UpdateRace :execrows
UPDATE races SET name = $1 WHERE id = $2
`

type UpdateRaceParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) UpdateRace(ctx context.Context, arg UpdateRaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRace, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
