// Code generated by swaggo/swag. DO NOT EDIT.
// Run `make generate` to regenerate.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{"swagger":"2.0","info":{"title":"Character API","description":"キャラクター管理 REST API","contact":{},"version":"1.0"},"host":"localhost:8080","basePath":"/","paths":{}}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Character API",
	Description:      "キャラクター管理 REST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
